'use client'

import { useState, useEffect, useCallback } from 'react'
import { useAuth } from '../contexts/AuthContext'
import { getApiUrl } from '../utils/api'
import axios from 'axios'
import { Plus, Sparkles, Clock, Trash2, Loader2, Zap, X, Eye, Repeat, ThumbsUp } from 'lucide-react'
import PromotionWizard from './PromotionWizard'

interface Promotion {
  _id: string
  title: string
  description?: string
  offer?: string
  type: string
  discount?: number
  pricePoint?: { originalPrice: number; specialPrice: number }
  isActive: boolean
  startTime?: string
  endTime?: string
  isFlashDeal?: boolean
  isRecurring?: boolean
  autoGenerated?: boolean
}

interface AISuggestion {
  type: string
  priority: string
  title: string
  description: string
  suggestedPromotion: any
  confidence: number
}

const DEAL_EMOJI: Record<string, string> = {
  'happy-hour': '🧋', 'flash-deal': '⚡', 'special': '🎉', 'exclusive': '👑', 'event': '🎪',
  'slow-right-now': '🔥', 'slow-day-boost': '📈', 'peak-optimization': '🧋',
  'replicate-success': '🔁', 'revenue-trend': '⚡', 'retention': '💌',
  'strong-day-note': '💪', 'seasonal': '🎄',
}

export default function DealsTab() {
  const { venue, token } = useAuth()
  const [promotions, setPromotions] = useState<Promotion[]>([])
  const [aiSuggestions, setAiSuggestions] = useState<AISuggestion[]>([])
  const [loading, setLoading] = useState(true)
  const [showWizard, setShowWizard] = useState(false)
  const [deleting, setDeleting] = useState<string | null>(null)
  const [approvingAI, setApprovingAI] = useState<number | null>(null)

  const fetchData = useCallback(async () => {
    if (!token || !venue?.id) return
    setLoading(true)
    try {
      const [promoRes, aiRes] = await Promise.allSettled([
        axios.get(`${getApiUrl()}/venues/${venue.id}`, { headers: { Authorization: `Bearer ${token}` } }),
        axios.get(`${getApiUrl()}/ai-automation/suggestions?venueId=${venue.id}`, { headers: { Authorization: `Bearer ${token}` } }),
      ])
      if (promoRes.status === 'fulfilled') {
        const v = promoRes.value.data.venue || promoRes.value.data
        const now = new Date()
        const active = (v.promotions || []).filter((p: Promotion) => {
          if (!p.isActive) return false
          if (p.endTime && new Date(p.endTime) < now) return false
          return true
        })
        setPromotions(active)
      }
      if (aiRes.status === 'fulfilled') {
        setAiSuggestions((aiRes.value.data.suggestions || []).slice(0, 3))
      }
    } catch { /* ignore */ } finally {
      setLoading(false)
    }
  }, [token, venue?.id])

  useEffect(() => { fetchData() }, [fetchData])

  const handleSave = async (data: any) => {
    if (!token || !venue?.id) return
    await axios.post(`${getApiUrl()}/venues/${venue.id}/promotions`, data, {
      headers: { Authorization: `Bearer ${token}` }
    })
    setShowWizard(false)
    fetchData()
  }

  const handleDelete = async (promoId: string) => {
    if (!token || !venue?.id) return
    setDeleting(promoId)
    try {
      await axios.delete(`${getApiUrl()}/venues/${venue.id}/promotions/${promoId}`, {
        headers: { Authorization: `Bearer ${token}` }
      })
      setPromotions(prev => prev.filter(p => p._id !== promoId))
    } catch { /* ignore */ } finally {
      setDeleting(null)
    }
  }

  const approveAI = async (idx: number) => {
    if (!token || !venue?.id) return
    setApprovingAI(idx)
    try {
      const suggestion = aiSuggestions[idx]
      await axios.post(`${getApiUrl()}/ai-automation/suggestions/apply`, {
        venueId: venue.id,
        suggestionIndex: idx,
        suggestion
      }, { headers: { Authorization: `Bearer ${token}` } })
      setAiSuggestions(prev => prev.filter((_, i) => i !== idx))
      fetchData()
    } catch { /* ignore */ } finally {
      setApprovingAI(null)
    }
  }

  return (
    <div className="flex-1 overflow-y-auto pb-24 px-5" style={{ background: '#0F0F1E' }}>
      {/* Header */}
      <div className="flex items-center justify-between pt-6 pb-4">
        <div>
          <h1 className="text-xl font-black text-white" style={{ fontFamily: 'Poppins, sans-serif' }}>Deals</h1>
          <p className="text-xs text-white/30 mt-0.5">Create and manage your promotions</p>
        </div>
        <button
          onClick={() => setShowWizard(true)}
          className="flex items-center gap-1.5 px-4 py-2.5 rounded-xl text-sm font-bold transition-all"
          style={{ background: '#C8F135', color: '#0F0F1E' }}
        >
          <Plus className="w-4 h-4" /> New Deal
        </button>
      </div>

      {/* AI Suggestions */}
      {aiSuggestions.length > 0 && (
        <div className="mb-5">
          <p className="text-[10px] font-bold uppercase tracking-wider mb-2" style={{ color: 'rgba(200,241,53,0.5)' }}>
            <Sparkles className="w-3 h-3 inline mr-1" />AI Recommends
          </p>
          <div className="space-y-2">
            {aiSuggestions.map((s, idx) => (
              <div key={idx} className="rounded-xl p-3.5 flex items-start gap-3" style={{ background: 'rgba(200,241,53,0.04)', border: '1px solid rgba(200,241,53,0.12)' }}>
                <span className="text-lg mt-0.5">{DEAL_EMOJI[s.suggestedPromotion?.type] || '🎯'}</span>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-semibold text-white">{s.title}</p>
                  <p className="text-[11px] text-white/35 mt-0.5 line-clamp-2">{s.description}</p>
                </div>
                <button
                  onClick={() => approveAI(idx)}
                  disabled={approvingAI === idx}
                  className="flex items-center gap-1 px-3 py-1.5 rounded-lg text-[11px] font-bold disabled:opacity-40 min-h-[32px] flex-shrink-0"
                  style={{ background: '#C8F135', color: '#0F0F1E' }}
                >
                  {approvingAI === idx ? <Loader2 className="w-3 h-3 animate-spin" /> : <><ThumbsUp className="w-3 h-3" /> Go Live</>}
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Active Deals */}
      {loading ? (
        <div className="space-y-3">
          {[1, 2, 3].map(i => <div key={i} className="rounded-2xl h-20 animate-pulse" style={{ background: '#1C1C32' }} />)}
        </div>
      ) : promotions.length === 0 ? (
        <div className="fv-card py-12 text-center">
          <p className="text-3xl mb-3">🧋</p>
          <p className="text-white/50 text-sm font-semibold">No active deals</p>
          <p className="text-white/25 text-xs mt-1">Create your first deal to start attracting customers</p>
        </div>
      ) : (
        <div className="space-y-2">
          <p className="text-[10px] font-bold uppercase tracking-wider text-white/30 mb-2">Active Deals ({promotions.length})</p>
          {promotions.map(p => (
            <div key={p._id} className="fv-card px-4 py-3.5 flex items-start gap-3">
              <span className="text-xl mt-0.5 flex-shrink-0">{DEAL_EMOJI[p.type] || '🎯'}</span>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <p className="text-sm font-semibold text-white truncate">{p.title}</p>
                  {p.isRecurring && <Repeat className="w-3 h-3 flex-shrink-0" style={{ color: '#00D4FF' }} />}
                  {p.isFlashDeal && <Zap className="w-3 h-3 flex-shrink-0" style={{ color: '#FF9A57' }} />}
                </div>
                {p.description && <p className="text-[11px] text-white/30 mt-0.5 line-clamp-1">{p.description}</p>}
                {p.endTime && (
                  <p className="text-[10px] text-white/20 mt-1 flex items-center gap-1">
                    <Clock className="w-3 h-3" /> Ends {new Date(p.endTime).toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}
                  </p>
                )}
              </div>
              <button
                onClick={() => handleDelete(p._id)}
                disabled={deleting === p._id}
                className="w-8 h-8 rounded-lg flex items-center justify-center hover:bg-white/5 transition-colors flex-shrink-0"
              >
                {deleting === p._id ? <Loader2 className="w-4 h-4 text-white/20 animate-spin" /> : <Trash2 className="w-4 h-4 text-white/20" />}
              </button>
            </div>
          ))}
        </div>
      )}

      {/* Wizard modal */}
      {showWizard && (
        <PromotionWizard
          onSave={handleSave}
          onCancel={() => setShowWizard(false)}
        />
      )}
    </div>
  )
}
