const mongoose = require('mongoose');

const venueSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
    trim: true
  },
  slug: {
    type: String,
    trim: true,
    lowercase: true
  },
  owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  address: {
    street: String,
    city: String,
    state: String,
    zipCode: String,
    country: { type: String, default: 'US' }
  },
  location: {
    type: {
      type: String,
      enum: ['Point'],
      default: 'Point'
    },
    coordinates: {
      type: [Number], // [longitude, latitude]
      required: true
    }
  },
  description: String,
  coverPhoto: { type: String, default: '' },
  category: {
    type: String,
    enum: [
      // SOM (nightlife)
      'restaurant', 'bar', 'cafe', 'club', 'other',
      // Fizz (non-alcohol / family-friendly)
      'coffee shop', 'juice bar', 'dirty soda shop', 'soda shop',
      'tea house', 'smoothie bar', 'bakery', 'ice cream', 'creamery',
    ],
    default: 'other'
  },
  /** Which consumer app(s) this venue appears in */
  platform: {
    type: String,
    enum: ['som', 'fizz', 'both'],
    default: 'som'
  },
  isActive: {
    type: Boolean,
    default: true
  },
  // Subscription and promotion features
  subscriptionTier: {
    type: String,
    enum: ['free', 'basic', 'premium', 'enterprise'],
    default: 'free'
  },
  isFeatured: {
    type: Boolean,
    default: false
  },
  featuredUntil: Date, // When featured status expires
  subscriptionExpiresAt: Date, // When subscription expires
  promotions: [{
    title: String,
    description: String,
    discount: Number,
    validUntil: Date,
    isActive: { type: Boolean, default: true },
    type: { type: String, enum: ['happy-hour', 'special', 'event', 'flash-deal', 'exclusive', 'birthday', 'anniversary', 'other'], default: 'other' },
    startTime: Date,
    endTime: Date,
    schedule: [{
      days: String,
      start: String,
      end: String
    }],
    // Enhanced promotion features
    isExclusive: { type: Boolean, default: false }, // Only visible to app users
    isFlashDeal: { type: Boolean, default: false }, // Time-limited deal
    flashDealEndsAt: Date, // When flash deal expires
    pointsReward: { type: Number, default: 0 }, // Points earned for using this promotion
    maxUses: Number, // Maximum number of times this can be used
    currentUses: { type: Number, default: 0 },
    image: String, // Promotion image
    terms: String, // Terms and conditions
    pricePoint: {
      originalPrice: Number,
      specialPrice: Number,
      currency: { type: String, default: 'USD' }
    },
    // Analytics tracking
    analytics: {
      views: { type: Number, default: 0 }, // How many times promotion was viewed
      clicks: { type: Number, default: 0 }, // How many times promotion was clicked
      shares: { type: Number, default: 0 }, // How many times promotion was shared
      redemptions: { type: Number, default: 0 }, // Actual redemptions
      revenue: { type: Number, default: 0 }, // Revenue generated
      lastViewed: Date, // Last time someone viewed this promotion
      viewHistory: [{
        date: Date,
        count: Number
      }],
      lastViralAt: Date  // Timestamp of last viral moment detection (prevents re-trigger within 2h)
    },
    // Recurring promotion features
    isRecurring: { type: Boolean, default: false }, // Is this a recurring promotion
    recurrencePattern: {
      type: { type: String, enum: ['daily', 'weekly', 'monthly', 'custom'], default: 'weekly' },
      frequency: { type: Number, default: 1 }, // Every X days/weeks/months
      daysOfWeek: [{ type: Number }], // 0-6 (Sunday-Saturday) for weekly
      dayOfMonth: Number, // For monthly (1-31)
      endDate: Date, // When to stop recurring
      maxOccurrences: Number
    },
    // AI Automation fields
    autoGenerated: { type: Boolean, default: false }, // Was this promotion auto-generated by AI?
    aiConfidence: { type: Number, min: 0, max: 1 }, // AI confidence score (0-1)
    aiSuggestionId: String, // Reference to the AI suggestion that created this
    parentPromotionId: String, // Reference to original recurring promotion
    // Targeting options
    targeting: {
      followersOnly: { type: Boolean, default: false }, // Only show to venue followers
      locationBased: { type: Boolean, default: false }, // Target users within radius
      radiusMiles: { type: Number, default: 5 }, // Radius in miles for location targeting
      userSegments: [{ type: String, enum: ['all', 'frequent', 'vip', 'new'] }], // Target user segments
      minCheckIns: { type: Number, default: 0 }, // Minimum check-ins at venue to see promotion
      timeBased: { type: Boolean, default: false }, // Only show during specific times
      timeWindow: {
        start: String, // e.g., "17:00" for 5 PM
        end: String    // e.g., "19:00" for 7 PM
      }
    }
  }],
  schedule: {
    monday: { open: String, close: String, closed: { type: Boolean, default: false } },
    tuesday: { open: String, close: String, closed: { type: Boolean, default: false } },
    wednesday: { open: String, close: String, closed: { type: Boolean, default: false } },
    thursday: { open: String, close: String, closed: { type: Boolean, default: false } },
    friday: { open: String, close: String, closed: { type: Boolean, default: false } },
    saturday: { open: String, close: String, closed: { type: Boolean, default: false } },
    sunday: { open: String, close: String, closed: { type: Boolean, default: false } }
  },
  stripeAccountId: {
    type: String,
    default: null
    // Index defined below - don't use sparse: true here to avoid duplicate
  },
  followers: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }],
  followerCount: {
    type: Number,
    default: 0
  },
  aiAutomation: {
    enabled: { type: Boolean, default: false },
    autoPostThreshold: { type: Number, default: 0.85 },
    autoNotifyFollowers: { type: Boolean, default: true },
    autoGenerateSpecials: { type: Boolean, default: true },
    checkIntervalHours: { type: Number, default: 24 },
    maxPromotionsPerCycle: { type: Number, default: 2 },
    lastRunAt: Date
  },
  rating: {
    average: { type: Number, default: 0, min: 0, max: 5 },
    count: { type: Number, default: 0 }
  },
  // Venue referral reward configuration
  referralRewards: {
    baseCheckIn: {
      type: Number,
      default: 10 // Base points for referrer when friend checks in
    },
    eventCheckIn: {
      type: Number,
      default: 15 // Bonus points for event check-ins
    },
    recipientBonus: {
      type: Number,
      default: 5 // Bonus points for recipient checking in via referral
    },
    maxPerDay: {
      type: Number,
      default: 10 // Max referral rewards per day for referrer
    },
    maxPerWeek: {
      type: Number,
      default: 50 // Max referral rewards per week for referrer
    },
    enabled: {
      type: Boolean,
      default: true // Venue can disable referrals
    }
  },
  // AI learning feedback loop results (updated weekly)
  aiLearning: {
    typePerformance: { type: mongoose.Schema.Types.Mixed, default: {} },
    bestType: String,
    bestDay: String,
    bestHour: Number,
    promotionsAnalyzed: { type: Number, default: 0 },
    lastTrainedAt: Date
  },
  // Viral moment event log (last 30 events, capped in service layer)
  viralEvents: [{
    promotionId: mongoose.Schema.Types.ObjectId,
    promotionTitle: String,
    detectedAt: { type: Date, default: Date.now },
    recentViews: Number,
    multiplier: mongoose.Schema.Types.Mixed
  }],
  branding: {
    frameColor: { type: String, default: '#00FF88' },
    tagline: { type: String, maxlength: 60, default: '' },
    logoUrl: { type: String, default: '' }
  },
  website: { type: String, default: '' },        // Venue's own website URL
  placeId: { type: String, default: '' },        // Google Places ID for matching
  amenities: {
    kidsFriendly:   { type: Boolean, default: false },
    dogFriendly:    { type: Boolean, default: false },
    hasFood:        { type: Boolean, default: false },
    byob:           { type: Boolean, default: false },
    trivia:         { type: Boolean, default: false },
    liveMusic:      { type: Boolean, default: false },
    outdoorSeating: { type: Boolean, default: false },
    happyHour:      { type: Boolean, default: false },
    poolTables:     { type: Boolean, default: false },
    danceFloor:     { type: Boolean, default: false },
    sportsTv:       { type: Boolean, default: false },
    karaoke:        { type: Boolean, default: false },
    arcade:         { type: Boolean, default: false },
  },
}, {
  timestamps: true
});

// Index for geospatial queries
venueSchema.index({ location: '2dsphere' });
venueSchema.index({ owner: 1 });
venueSchema.index({ isActive: 1 });
venueSchema.index({ slug: 1 }, { unique: true, sparse: true });
venueSchema.index({ stripeAccountId: 1 }, { unique: true, sparse: true }); // Unique Stripe account IDs

module.exports = mongoose.model('Venue', venueSchema);
